### ISSUE TITLE
End of script error

### ISSUE THREAD

**Issue by bobhaslett** [rjduran/adobe-scripting#1]
I have a couple of scripts I'd like to expand. I've installed you shell for Atom as it looks so much better than using the Adobe provided editor. However, I get the following error when running a script

Executed : osascript -e 'tell application "Adobe Illustrator"' -e 'activate' -e 'do javascript "#include '/Volumes/GoogleDrive/Team Drives/Graphics - Production/In progress/London/Bob Haslett/AI scripts/4Print V2.0.jsx'"' -e 'end tell'
Returned with code 1
61:61: syntax error: Expected string but found end of script. (-2741)

**Comment by rjduran** [comment]
The issue you are encountering here is due to having spaces in the path. I have only tested the workflow using `osascript` with paths without spaces. The easy solution is to put scripts in a path without spaces in folders or filenames. For example, ~/AIScripts/script.jsx.

**Comment by rjduran** [comment]
Closing this for now. The best solution at this time is to use paths without spaces.

**Comment by rjduran** [comment]
Just discovered another Atom package that solves the issue of using spaces. https://atom.io/packages/adobe-script-runner

I'm currently updating the readme to include a few new workflows.
